### ISSUE TITLE
Big banner for homepage.

### ISSUE THREAD

**Issue by hashbrowncipher** [cwruacm/acm.case.edu#13]
@bis12  informs me that the current homepage doesn't have a GIANT banner inviting people to the conference.  It really should.  This is important.

**Comment by thomasrussellmurphy** [comment]
Nearly 3 years later, still relevant. Thoughts?

**Comment by thomasrussellmurphy** [comment]
Seeing no thoughts, I'll close this because the conference is currently the first thing on the homepage.
