### ISSUE TITLE
Add explanation of Link-State conference name

### ISSUE THREAD

**Issue by mrb113** [cwruacm/acm.case.edu#27]
I know it has something to do with the link-state routing protocol and I remember it was really cute, but the connection between the two escapes me. Nobody else seems to know it, either, so someone who remembers the connection should add it to the conference page so that it won't be forgotten over the years :) http://acm.case.edu/acm/conference/about

**Comment by thomasrussellmurphy** [comment]
Bump for further thought on actually doing something with this?

**Comment by iandimayuga** [comment]
I see no reason the above shouldn't be used verbatim :)

Though it probably shouldn't switch from present to past tense partway through.
