### ISSUE TITLE
Put link to deployed version in repo description

### ISSUE THREAD

**Issue by thomasrussellmurphy** [cwruacm/acm.case.edu#39]
Put something like `Deployed at http://acm.case.edu/` or `Lives at http://acm.case.edu/` in the repository description. Needs an owner to edit.

**Comment by StephHippo** [comment]
You should be able to submit a Pull Request.

**Comment by thomasrussellmurphy** [comment]
I don't think I can. This would work best in the Website field of the description at the top of the repo.

**Comment by StephHippo** [comment]
Have you tried since my comment? You're now marked as a collaborator. You should be able to actually directly push to the repo.

**Comment by thomasrussellmurphy** [comment]
(Not README.md). I still can't edit the `Shiny website for the EECS cabal` line. See the description at the top of https://github.com/thomasrussellmurphy/acm.case.edu

**Comment by thomasrussellmurphy** [comment]
Now fixed.
